# NumPy Codes

In [1]:
# Import numpy library
import numpy as np
import os

### Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[8.0,6.0,7.0],[6.0,5.0,4.0]])
print(b)

[[8. 6. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimention
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [11]:
a.itemsize

4

In [12]:
b.itemsize

8

In [13]:
# Get total size
a.nbytes

12

In [14]:
b.nbytes

48

### Accesssing/Changing specific elements, row, columns, etc

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
a.shape

(2, 7)

In [27]:
# Get a specific element [r, c] row, column
a[1,5] # or you can use a[1,-2]

13

In [28]:

# To get a specific row (the first row) a[0,:]
a[0,:]


array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# To get a specific row (the second row) a[1,:]
a[1,:]


array([ 8,  9, 10, 11, 12, 13, 14])

In [30]:
# To get a specific column (the first column) a[:,0]
a[:,0]

array([1, 8])

In [31]:
# To get a specific column (the second column) a[:,1]
a[:,1]

array([2, 9])

In [35]:
# Getting a bit deeper(Let's access a specific element) [start_index: end_index:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [36]:
# another way to do this -- Getting a bit deeper(Let's access a specific element) [start_index: end_index:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [37]:
# Changing the value of an element in the first row 

a[0,5]=20
print(a)

[[ 1  2  3  4  5 20  7]
 [ 8  9 10 11 12 13 14]]


In [38]:
# Changing the value of an element in the second row 

a[1,5]=20
print(a)

[[ 1  2  3  4  5 20  7]
 [ 8  9 10 11 12 20 14]]


In [40]:
# Changing the value of elements in column 2 in all rows to be all 5 in the second row 
a[:,2]=5
print(a)

[[ 1  2  5  4  5 20  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
# Changing the value of elements in column 2 in all rows to be [1,2] in the second row 
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5 20  7]
 [ 8  9  2 11 12 20 14]]


### 3-dimension exaple

In [43]:
b = np.array([[[1,2],[2,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [2 4]]

 [[5 6]
  [7 8]]]


### Getting specific segment, rows and columns
#### (work outside in) [segment:row:column]

In [58]:
# Getting specific elements[segment:row:column]
b[0,1,1]

4

In [59]:
# All segments, row, and columns
b[:,:,:]

array([[[1, 2],
        [2, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
# All segments, all row, but first columns
b[:,:,0]

array([[1, 2],
       [5, 7]])

In [61]:
# All segments, all row, but second columns
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [64]:
# All segments, all row, and first columns
b[:,:,0]

array([[1, 2],
       [5, 7]])

In [65]:
# All segments, second row, and all columns
b[:,1,:]

array([[2, 4],
       [7, 8]])

In [66]:
# Replace
b[:,1,:]

array([[2, 4],
       [7, 8]])

In [69]:
# Replace to [9,9]
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different types of Arrays

In [70]:
# Initial All Zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
# Initial All Zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
# Initial All ones matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [73]:
# Initial All ones matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [80]:
# Initial Any other number matrix using "np.full" [matrix, values]
np.full((2,2),77)

array([[77, 77],
       [77, 77]])

In [81]:
# Initial Any other number matrix using "np.full" [matrix, values]
np.full((2,2),77, dtype='float32')

array([[77., 77.],
       [77., 77.]], dtype=float32)

In [83]:
# Initial Any other number matrix using "np.full" [matrix, values]
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [85]:
# Another way: # Initial Any other number matrix using "np.full" [matrix, values]
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Generating Random Numbers

In [86]:
# Random decimal numbers btw 0 & 1
np.random.rand(4,2)

array([[0.85874315, 0.91501588],
       [0.73141458, 0.25029847],
       [0.58790335, 0.91616783],
       [0.4192358 , 0.40259383]])

In [87]:
# Random decimal numbers btw 0 & 1 in 3-D
np.random.rand(3,2,2)

array([[[0.48106617, 0.74864277],
        [0.79023686, 0.10127615]],

       [[0.2467559 , 0.29400851],
        [0.41424094, 0.41922134]],

       [[0.09330294, 0.81201473],
        [0.62579288, 0.13371828]]])

In [89]:
# Random decimal numbers from a array
np.random.random_sample(a.shape)

array([[0.93412656, 0.71040528, 0.96154938, 0.29876638, 0.80701015,
        0.31628608, 0.71994639],
       [0.20273283, 0.88187008, 0.02539291, 0.52226313, 0.50523163,
        0.33433306, 0.95098323]])

In [97]:
# generate Random integer numbers from 0 to 6 inclusive
np.random.randint(7, size=(3,3))

array([[6, 2, 2],
       [6, 2, 5],
       [0, 4, 5]])

In [100]:
# generate Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
# Repeating Arrays a few times
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)
          

[1 1 1 2 2 2 3 3 3]


In [106]:
# Repeating Arrays a few times
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [113]:
# Task
out = np.ones((5,5))
print(out)

z = np.zeros((3,3))
z[1,1]=9
print(z)

out[1:-1,1:-1]=z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying arrays (be careful)

In [130]:
a =np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [116]:
b=a
b[0]=9
print(a)

[9 2 3]


In [119]:
b=a.copy()
b[0]=9
print(a)

[1 2 3]


### Mathematics
#### Element-wise arithmetics

In [127]:
a =np.array([1,2,3])
print(a)

[1 2 3]


In [121]:
# Element-wise addition
a+2

array([3, 4, 5])

In [122]:
# Element-wise multiplication
a*2

array([2, 4, 6])

In [123]:
# Element-wise subtraction
a-2

array([-1,  0,  1])

In [124]:
# Element-wise division
a/2

array([0.5, 1. , 1.5])

In [125]:
# Element-wise power of 2
a**2

array([1, 4, 9], dtype=int32)

In [131]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [134]:
a*b

array([1, 0, 3, 0])

In [132]:
# Take Sin and cosin of values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [133]:
# Take Sin and cosin of values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [137]:
a =np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [138]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [141]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [142]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
# Getting the minimum value 
np.min(stats)

1

In [145]:
# Getting the minimum value in the first row
np.min(stats, axis=0)

array([1, 2, 3])

In [146]:
# Getting the minimum value in the first row
np.min(stats, axis=1)

array([1, 4])

In [144]:
# Getting the maximum value
np.max(stats)

6

In [148]:
# getting total summation of all values in the matrix
np.sum(stats)

21

### Reorganizing Arrays

In [154]:
# vdimension should be the same
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((3,2))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [171]:
# Vertical Stacking
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [167]:
# Horizontal Stacking [The dimension for the number of rows must be equal]
h1=np.ones((2,1))
h2=np.zeros((2,2))
np.hstack((h1,h2,h1,h2))

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.]])

### Load Data file

In [183]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 12., 13., 14., 15.,
        16., 17.],
       [10., 11., 21., 22., 23., 24., 25., 26., 27., 18., 19., 20.,  2.,
         3.,  4.],
       [10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1., 31., 32., 34.,
        35., 36.]])

In [184]:
filedata.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 17],
       [10, 11, 21, 22, 23, 24, 25, 26, 27, 18, 19, 20,  2,  3,  4],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 31, 32, 34, 35, 36]])

In [185]:
filedata=filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 13, 14, 15, 16, 17],
       [10, 11, 21, 22, 23, 24, 25, 26, 27, 18, 19, 20,  2,  3,  4],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 31, 32, 34, 35, 36]])

### Boolean Masking and indexing

In [188]:
# get values that are greater than 20
filedata>20

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True]])

In [189]:
# List the elements with values greater than 20
filedata[filedata>20]

array([21, 22, 23, 24, 25, 26, 27, 31, 32, 34, 35, 36])

In [193]:
# How to index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [197]:
# getting values greater than 20 in the first row
np.any(filedata>20, axis=0)

array([False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True])

In [198]:
# getting values greater than 20 in the second row
np.any(filedata>20, axis=1)

array([False,  True,  True])

In [201]:
((filedata>20) & (filedata<30))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False]])

In [202]:
(~((filedata>20) & (filedata<30)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False, False, False, False,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])